name: Embedded Cloud Benchmark
on:
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  benchmark:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 5
      matrix:
        DBNAME: [ "chdb", "duckdb", "glaredb", "databend", "datafusion" ]
  
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Benchmark ${{ matrix.DBNAME }}
      env:
        ITERATIONS: ${{ github.event.inputs.ITERATIONS || 3 }}
        DBNAME: ${{ matrix.DBNAME }}
      run: |
        cd ${{ matrix.DBNAME }}
        ./benchmark.sh

    - uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        pull: '--no-edit'

  report:
    needs: benchmark
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Pull latest
      run: git pull --no-edit
      
    - name: Setup Pages
      uses: actions/configure-pages@v3
      
    - name: Generate Results
      run: |
        ./generate-results.sh
        mkdir public
        cp index.html public/

    - uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: 'public'
          
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
